os: linux
dist: xenial
language: python
python:
  - '3.6-dev'
  - '3.7-dev'
services:
  - xvfb
before_install:
  - export PATH=/usr/bin:$PATH
  - sudo apt-get update -q
  # Dependency to build dbus-python
  - sudo apt-get install libdbus-1-dev
  # Dependency to build python-discid
  - sudo apt-get install libdiscid0
  # Dependencies for GStreamer1.0
  - sudo apt-get install --yes gstreamer1.0-alsa gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-libav
  # Dependencies for gi.repository: Gst, GObject, Cairo
  - sudo apt-get install -y libgirepository1.0-dev libcairo2-dev gir1.2-gtk-3.0 gobject-introspection python3-gi python3-gi-cairo gir1.2-gtk-3.0 python3-gst-1.0
  # Tricks to avoid gstreamer error about X11:
  # 'Gtk3 requires X11, and no DISPLAY environment variable is set'
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
  - sudo apt-get install -y xvfb
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - pip install --upgrade setuptools
  - pip install --upgrade cython
  - pip install pycairo
  - pip install pygobject
  - pip install https://github.com/lobocv/eventdispatcher/archive/1.9.4.tar.gz
  - pip install -e git+https://github.com/freedesktop/dbus-python@master#egg=dbus-python --no-dependencies
  - pip install -e git+https://github.com/fishstiqz/pycdb@master#egg=pycdb --no-dependencies
  - pip install -e git+https://github.com/JonnyJD/python-discid@master#egg=discid --no-dependencies
  - pip install git+git://github.com/opacam/epsilon@python3#egg=Epsilon
  - pip install git+git://github.com/opacam/axiom@python3#egg=Axiom
  - pip install git+https://github.com/dvska/gdata-python3#egg=gdata
  - pip install autobahn
  - pip install feedparser
  - pip install livestreamer
  - pip install service_identity
  - pip install python-coveralls==2.9.1
  - pip install pycodestyle==2.4.0
  - pip install pylint==2.1.1
  - pip install travis-sphinx
  - pip install sphinx-rtd-theme
  - pip install -e .[test]
script:
  - pycodestyle coherence --ignore=E402,W504
  - pylint -E coherence --rcfile=.pylintrc
  - nosetests --config=.noserc
  - travis-sphinx build -n --source=docs
after_success:
  - travis-sphinx deploy
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  skip_cleanup: true
#  user: opacam
#  password:
#    secure: fLJVFsyO3VIFMLG7S5HQoyzYLsIBZZiI+f8iwpxxCN8gjwKe5WadoTEBgtATpTZrkfrza61xRABBd8hrn5+dZTRcebodD0oSrZEttB15WYLDXZucVGWY1jmKCpjM5I1BzJTr6kMbOCr+bwewM30izW1mXKHsUzqRc+TarKpIKUlOoYGB65KWLKGilreGVft8Vmx58Q4/xMb3Uax5LQzDtePZmAnpXDMAD12zSGCMeHKZHDFCoTBxeij1unRIW9Bq+l/1F4Uh22gd7HWS0dkQBRQXojjqETVZgvssxfOSuQTgluvZpnjjk5obntJIitx7q924dCBKO8vq1wGF5my9jg3BFeAOkRJnM6n1+9n8e7JgC8+zQrBqlf9BuUhnBOS2rQpnc9nnD5AfL/Hsh5GcJJ06AXrxGNiVaKKT2oVwesrRrPFXW6l9vknrhza9Zy0mDqDdGLHGzEpGc+C55iKcrQzmQ4/TSqCruhBI4B3alO+zAV8cLdRxNAOwKthx60p/DjeMjyFEt5DIEtAfZfr5Jbx8k6sW72vdBrLXMX4JZIg6XmRm/buCqASEvulkd/j9/L4wBnbQJJQ6VYPlDlvzslq/NJavlko4Z/oBAJ/So4dhtJFi/g0hUIHx+40k0o8RbptRYu5vm5fALonHM0tvm3KGZyymPbn5k5OwouHFZd8=
#  on:
#    tags: true
